return {
	Progression = {
		BaseXpForLevel = 100,
		XpGrowthPerLevel = 35,
		BaseWalkSpeed = 16,
		BaseMaxHealth = 100,
		SkillOrder = { "Speed", "MeleeDamage", "RangedDamage", "Health" },
		Skills = {
			Speed = {
				DisplayName = "Speed",
				MaxLevel = 8,
				WalkSpeedPerLevel = 1.8,
			},
			MeleeDamage = {
				DisplayName = "Melee Damage",
				MaxLevel = 8,
				DamageMultiplierPerLevel = 0.12,
			},
			RangedDamage = {
				DisplayName = "Ranged Damage",
				MaxLevel = 8,
				DamageMultiplierPerLevel = 0.1,
			},
			Health = {
				DisplayName = "Max Health",
				MaxLevel = 8,
				MaxHealthPerLevel = 20,
			},
		},
	},

	Lobby = {
		CombatPlaceId = 81561302455824,
		MaxPartySize = 6,
		DefaultPartySize = 2,
		DefaultPadCount = 2,
		QueueTouchDebounceSeconds = 1.0,
	},

	Classes = {
		DefaultClass = "Assault",
		Order = { "Assault", "Builder", "Healer", "Melee" },
		Definitions = {
			Assault = {
				DisplayName = "Assault",
				StarterWeapons = { "Rifle" },
			},
			Builder = {
				DisplayName = "Builder",
				StarterWeapons = { "Shotgun" },
			},
			Healer = {
				DisplayName = "Healer",
				StarterWeapons = { "Bow" },
			},
			Melee = {
				DisplayName = "Melee",
				StarterWeapons = { "Bulava" },
			},
		},
	},

	MetaProgression = {
		DataStoreName = "HeroicSurvivalProfile_v1",
		AutoSaveIntervalSeconds = 90,
		UpgradeOrder = { "Damage", "Health", "Speed" },
		Upgrades = {
			Damage = {
				DisplayName = "Damage",
				MaxLevel = 20,
				BaseCost = 5,
				CostStep = 5,
				RangedDamagePerLevel = 0.02,
				MeleeDamagePerLevel = 0.02,
			},
			Health = {
				DisplayName = "Health",
				MaxLevel = 20,
				BaseCost = 5,
				CostStep = 5,
				MaxHealthPerLevel = 4,
			},
			Speed = {
				DisplayName = "Speed",
				MaxLevel = 20,
				BaseCost = 5,
				CostStep = 5,
				WalkSpeedPerLevel = 0.12,
			},
		},
	},

	Zombies = {
		LobbyPlaceId = 135533599453315,
		DefaultDifficulty = "Medium",
		TargetWaveCount = 100,
		IntermissionSeconds = 12,
		BaseEnemiesPerWave = 8,
		EnemiesPerWaveStep = 1,
		BossWaveInterval = 10,
		BossAdditionalEnemies = 4,
		BossVariantKey = "BossBrute",
		Difficulties = {
			Easy = {
				DisplayName = "Easy",
				EnemyHealthMultiplier = 0.5,
				EnemyDamageMultiplier = 0.5,
				EnemyCountMultiplier = 0.5,
				RewardMultiplier = 0.5,
				CrystalMultiplier = 0.5,
			},
			Medium = {
				DisplayName = "Medium",
				EnemyHealthMultiplier = 1.0,
				EnemyDamageMultiplier = 1.0,
				EnemyCountMultiplier = 1.0,
				RewardMultiplier = 1.0,
				CrystalMultiplier = 1.0,
			},
			Hard = {
				DisplayName = "Hard",
				EnemyHealthMultiplier = 2.0,
				EnemyDamageMultiplier = 2.0,
				EnemyCountMultiplier = 2.0,
				RewardMultiplier = 2.0,
				CrystalMultiplier = 2.0,
			},
			Insane = {
				DisplayName = "Insane",
				EnemyHealthMultiplier = 4.0,
				EnemyDamageMultiplier = 4.0,
				EnemyCountMultiplier = 4.0,
				RewardMultiplier = 4.0,
				CrystalMultiplier = 4.0,
			},
		},
		PartyRewardBonusPerPlayer = 0.1,
		PartyEnemyCountBonusPerPlayer = 0.1,

		BaseMaxAlive = 10,
		BaseSpawnInterval = 3.8,
		MinSpawnInterval = 1.1,
		MaxAlivePerStage = 2,

		BaseHealth = 100,
		BaseMoveSpeed = 4.5,
		BaseAttackDamage = 10,
		BaseAttackRange = 4.5,
		BaseAttackCooldown = 1.2,
		BaseRewardMoney = 25,
		BaseRewardXP = 20,

		DifficultyStepSeconds = 60,
		HealthScalePerStage = 0.12,
		SpeedScalePerStage = 0.05,
		DamageScalePerStage = 0.1,
		RewardScalePerStage = 0.08,
		SpawnRateScalePerStage = 0.12,

		RespawnDelayIfTeammateAlive = 60,
		FreeRespawnBaseSeconds = 10,
		FreeRespawnIncrementSeconds = 10,
		WipePurchaseWindowSeconds = 30,
		ReviveProducts = {
			SoloReviveProductId = 3565038680,
			TeamReviveProductId = 3565038815,
		},
		ReviveDisplayPrices = {
			SoloReviveRobux = 10,
			TeamReviveRobux = 50,
		},
		RestartDelayAfterWipe = 12,

		KillCreditTimeout = 15,
		MinSpawnDistanceToPlayer = 20,

		Variants = {
			Walker = {
				DisplayName = "Walker",
				HealthMul = 1.0,
				MoveSpeedMul = 1.0,
				DamageMul = 1.0,
				RewardMul = 1.0,
				Color = { 77, 142, 74 },
				HeadColor = { 101, 170, 95 },
			},
			Crawler = {
				DisplayName = "Crawler",
				HealthMul = 0.8,
				MoveSpeedMul = 0.75,
				DamageMul = 0.9,
				RewardMul = 1.1,
				ScaleY = 0.55,
				Color = { 96, 128, 67 },
				HeadColor = { 118, 162, 84 },
			},
			Runner = {
				DisplayName = "Runner",
				HealthMul = 0.85,
				MoveSpeedMul = 1.75,
				DamageMul = 1.25,
				RewardMul = 1.3,
				Color = { 70, 120, 90 },
				HeadColor = { 88, 150, 110 },
			},
			Flyer = {
				DisplayName = "Flyer",
				HealthMul = 0.7,
				MoveSpeedMul = 1.35,
				DamageMul = 0.85,
				RewardMul = 1.45,
				FlyHeight = 9,
				Color = { 95, 88, 160 },
				HeadColor = { 125, 118, 185 },
			},
			Spitter = {
				DisplayName = "Spitter",
				HealthMul = 1.0,
				MoveSpeedMul = 0.95,
				DamageMul = 0.65,
				RewardMul = 1.6,
				SpitRange = 42,
				SpitDamage = 14,
				SpitCooldown = 2.4,
				SpitProjectileSpeed = 52,
				Color = { 65, 130, 64 },
				HeadColor = { 94, 170, 94 },
			},
			Bomber = {
				DisplayName = "Bomber",
				HealthMul = 0.9,
				MoveSpeedMul = 1.1,
				DamageMul = 0.8,
				RewardMul = 1.8,
				BossCrystalDrop = 1,
				ExplosionRange = 10,
				ExplosionDamage = 45,
				ExplosionTriggerRange = 6.5,
				Color = { 160, 88, 74 },
				HeadColor = { 194, 118, 95 },
			},
			BossBrute = {
				DisplayName = "Boss Brute",
				IsBoss = true,
				HealthMul = 6.0,
				MoveSpeedMul = 0.9,
				DamageMul = 2.5,
				RewardMul = 3.0,
				BossCrystalDrop = 3,
				Color = { 120, 55, 55 },
				HeadColor = { 175, 90, 90 },
			},
		},

		DifficultySchedule = {
			{ MinTime = 0, Weights = { Walker = 100 } },
			{ MinTime = 60, Weights = { Walker = 75, Crawler = 25 } },
			{ MinTime = 120, Weights = { Walker = 55, Crawler = 20, Runner = 25 } },
			{ MinTime = 180, Weights = { Walker = 40, Crawler = 20, Runner = 20, Spitter = 20 } },
			{ MinTime = 240, Weights = { Walker = 28, Crawler = 20, Runner = 20, Spitter = 20, Flyer = 12 } },
			{ MinTime = 300, Weights = { Walker = 20, Crawler = 15, Runner = 20, Spitter = 20, Flyer = 15, Bomber = 10 } },
		},
	},

	Pickups = {
		SpawnInterval = 12,
		Lifetime = 45,
		MaxNearbyPerPlayer = 5,
		MinRadius = 8,
		MaxRadius = 16,
		DefaultAmmoAmount = 10,
	},

	DefaultOwnedWeapons = { "Bulava" },
	ShopOrder = { "Pistol", "Rifle", "Shotgun", "Sniper", "Bow", "Bulava" },

	Weapons = {
		Pistol = {
			Key = "Pistol",
			ToolName = "Pistol",
			DisplayName = "Pistol",
			Category = "Ranged",
			Price = 200,
			MaxMag = 12,
			StartReserve = 36,
			MaxReserve = 180,
			FireCooldown = 0.2,
			ReloadTime = 1.5,
			Range = 320,
			Damage = 22,
			Pellets = 1,
			SpreadDegrees = 1.5,
			AmmoPackPrice = 30,
			AmmoPackAmount = 24,
			FireAnimationId = "rbxassetid://507777826",
			ReloadAnimationId = "rbxassetid://507777451",
			ShotSoundId = "rbxasset://sounds/swordslash.wav",
			ReloadSoundId = "rbxasset://sounds/unsheath.wav",
		},

		Rifle = {
			Key = "Rifle",
			ToolName = "Rifle",
			DisplayName = "Rifle",
			Category = "Ranged",
			Price = 450,
			MaxMag = 30,
			StartReserve = 90,
			MaxReserve = 360,
			FireCooldown = 0.09,
			ReloadTime = 2.2,
			Range = 380,
			Damage = 14,
			Pellets = 1,
			SpreadDegrees = 2.2,
			AmmoPackPrice = 55,
			AmmoPackAmount = 45,
			FireAnimationId = "rbxassetid://507770239",
			ReloadAnimationId = "rbxassetid://507777451",
			ShotSoundId = "rbxasset://sounds/impact_water.mp3",
			ReloadSoundId = "rbxasset://sounds/unsheath.wav",
		},

		Shotgun = {
			Key = "Shotgun",
			ToolName = "Shotgun",
			DisplayName = "Shotgun",
			Category = "Ranged",
			Price = 650,
			MaxMag = 6,
			StartReserve = 24,
			MaxReserve = 90,
			FireCooldown = 0.85,
			ReloadTime = 2.0,
			Range = 180,
			Damage = 12,
			Pellets = 7,
			SpreadDegrees = 7.5,
			AmmoPackPrice = 70,
			AmmoPackAmount = 12,
			FireAnimationId = "rbxassetid://507777268",
			ReloadAnimationId = "rbxassetid://507777451",
			ShotSoundId = "rbxasset://sounds/swordlunge.wav",
			ReloadSoundId = "rbxasset://sounds/unsheath.wav",
		},

		Sniper = {
			Key = "Sniper",
			ToolName = "Sniper",
			DisplayName = "Sniper",
			Category = "Ranged",
			Price = 900,
			MaxMag = 5,
			StartReserve = 20,
			MaxReserve = 80,
			FireCooldown = 1.2,
			ReloadTime = 2.7,
			Range = 700,
			Damage = 80,
			Pellets = 1,
			SpreadDegrees = 0.15,
			AmmoPackPrice = 95,
			AmmoPackAmount = 10,
			FireAnimationId = "rbxassetid://507776043",
			ReloadAnimationId = "rbxassetid://507777451",
			ShotSoundId = "rbxasset://sounds/electronicpingshort.wav",
			ReloadSoundId = "rbxasset://sounds/unsheath.wav",
		},

		Bow = {
			Key = "Bow",
			ToolName = "Bow",
			DisplayName = "Bow",
			Category = "Ranged",
			Price = 700,
			MaxMag = 1,
			StartReserve = 20,
			MaxReserve = 80,
			FireCooldown = 0.9,
			ReloadTime = 1.0,
			Range = 420,
			Damage = 45,
			Pellets = 1,
			SpreadDegrees = 0.9,
			AmmoPackPrice = 60,
			AmmoPackAmount = 10,
			FireAnimationId = "rbxassetid://507770677",
			ReloadAnimationId = "rbxassetid://507771019",
			ShotSoundId = "rbxasset://sounds/swordlunge.wav",
			ReloadSoundId = "rbxasset://sounds/unsheath.wav",
		},

		Bulava = {
			Key = "Bulava",
			ToolName = "Bulava",
			DisplayName = "Bulava",
			Category = "Melee",
			Price = 250,
			Damage = 40,
			Cooldown = 0.75,
			Range = 7,
			SwingAnimationId = "rbxassetid://522635514",
			SwingAltAnimationId = "rbxassetid://522638767",
			SwingSoundId = "rbxasset://sounds/swordlunge.wav",
		},
	},
}
