local config = {
	Progression = {
		BaseXpForLevel = 100,
		XpGrowthPerLevel = 35,
		BaseWalkSpeed = 16,
		BaseMaxHealth = 100,
		SkillOrder = { "Speed", "MeleeDamage", "RangedDamage", "Health" },
		Skills = {
			Speed = {
				DisplayName = "Speed",
				MaxLevel = 8,
				WalkSpeedPerLevel = 1.8,
			},
			MeleeDamage = {
				DisplayName = "Melee Damage",
				MaxLevel = 8,
				DamageMultiplierPerLevel = 0.12,
			},
			RangedDamage = {
				DisplayName = "Ranged Damage",
				MaxLevel = 8,
				DamageMultiplierPerLevel = 0.1,
			},
			Health = {
				DisplayName = "Max Health",
				MaxLevel = 8,
				MaxHealthPerLevel = 20,
			},
		},
	},

	Lobby = {
		CombatPlaceId = 135533599453315,
		MaxPartySize = 8,
		DefaultPartySize = 2,
		DefaultPadCount = 2,
		QueueTouchDebounceSeconds = 1.0,
	},

	Classes = {
		DefaultClass = "Gunner",
		Order = { "Gunner", "Guardian" },
		Definitions = {
			Gunner = {
				DisplayName = "Gunner",
				StarterWeapons = { "Pistol", "Rifle" },
			},
			Guardian = {
				DisplayName = "Guardian",
				StarterWeapons = { "Bulava" },
			},
		},
	},

	AchievementStats = {
		Order = {
			"RunsPlayed",
			"BestWave",
			"TotalKills",
			"BossKills",
		},
	},

	MetaProgression = {
		DataStoreName = "HeroicSurvivalProfile_v1",
		AutoSaveIntervalSeconds = 90,
		UpgradeOrder = { "Damage", "Health", "Speed" },
		Upgrades = {
			Damage = {
				DisplayName = "Damage",
				MaxLevel = 20,
				BaseCost = 5,
				CostStep = 5,
				RangedDamagePerLevel = 0.02,
				MeleeDamagePerLevel = 0.02,
			},
			Health = {
				DisplayName = "Health",
				MaxLevel = 20,
				BaseCost = 5,
				CostStep = 5,
				MaxHealthPerLevel = 4,
			},
			Speed = {
				DisplayName = "Speed",
				MaxLevel = 20,
				BaseCost = 5,
				CostStep = 5,
				WalkSpeedPerLevel = 0.12,
			},
		},
	},

	Zombies = {
		LobbyPlaceId = 81561302455824,
		DefaultDifficulty = "Medium",
		TargetWaveCount = 50,
		IntermissionSeconds = 12,
		BaseEnemiesPerWave = 8,
		EnemiesPerWaveStep = 1,
		BossWaveInterval = 10,
		BossAdditionalEnemies = 4,
		BossVariantKey = "BossStoneTitan",
		Difficulties = {
			Easy = {
				DisplayName = "Easy",
				EnemyHealthMultiplier = 0.5,
				EnemyDamageMultiplier = 0.5,
				EnemyCountMultiplier = 0.5,
				RewardMultiplier = 0.5,
				CrystalMultiplier = 0.5,
			},
			Medium = {
				DisplayName = "Medium",
				EnemyHealthMultiplier = 1.0,
				EnemyDamageMultiplier = 1.0,
				EnemyCountMultiplier = 1.0,
				RewardMultiplier = 1.0,
				CrystalMultiplier = 1.0,
			},
			Hard = {
				DisplayName = "Hard",
				EnemyHealthMultiplier = 2.0,
				EnemyDamageMultiplier = 2.0,
				EnemyCountMultiplier = 2.0,
				RewardMultiplier = 2.0,
				CrystalMultiplier = 2.0,
			},
			Insane = {
				DisplayName = "Insane",
				EnemyHealthMultiplier = 4.0,
				EnemyDamageMultiplier = 4.0,
				EnemyCountMultiplier = 4.0,
				RewardMultiplier = 4.0,
				CrystalMultiplier = 4.0,
			},
		},
		WaveTable = {
			{
				MinWave = 1,
				MaxWave = 1,
				BaseEnemiesPerWave = 8,
				EnemiesPerWaveStep = 2,
				MaxAlive = 14,
				SpawnInterval = 2.9,
				BossAdditionalEnemies = 3,
				Weights = { Runner = 55, Walker = 20, Crawler = 15, Shardling = 10 },
			},
			{
				MinWave = 2,
				MaxWave = 2,
				BaseEnemiesPerWave = 10,
				EnemiesPerWaveStep = 2,
				MaxAlive = 14,
				SpawnInterval = 2.9,
				BossAdditionalEnemies = 3,
				Weights = { Runner = 45, Hunter = 20, Walker = 10, Crawler = 10, Shardling = 10, MossBrute = 5 },
			},
			{
				MinWave = 3,
				MaxWave = 3,
				BaseEnemiesPerWave = 12,
				EnemiesPerWaveStep = 2,
				MaxAlive = 14,
				SpawnInterval = 2.9,
				BossAdditionalEnemies = 3,
				Weights = { Runner = 35, Hunter = 20, Walker = 10, Crawler = 10, Shardling = 15, MossBrute = 7, EmberWisp = 3 },
			},
			{
				MinWave = 4,
				MaxWave = 4,
				BaseEnemiesPerWave = 14,
				EnemiesPerWaveStep = 2,
				MaxAlive = 14,
				SpawnInterval = 2.9,
				BossAdditionalEnemies = 3,
				Weights = { Runner = 30, Hunter = 20, Walker = 10, Crawler = 10, Shardling = 15, MossBrute = 10, EmberWisp = 5 },
			},
			{
				MinWave = 5,
				MaxWave = 9,
				BaseEnemiesPerWave = 10,
				EnemiesPerWaveStep = 2,
				MaxAlive = 16,
				SpawnInterval = 2.5,
				BossAdditionalEnemies = 4,
				Weights = { Runner = 35, Hunter = 20, Walker = 10, Crawler = 8, Bruiser = 5, Shardling = 12, MossBrute = 7, EmberWisp = 3 },
			},
			{
				MinWave = 10,
				MaxWave = 24,
				BaseEnemiesPerWave = 11,
				EnemiesPerWaveStep = 1,
				MaxAlive = 13,
				SpawnInterval = 3.4,
				BossAdditionalEnemies = 5,
				Weights = { Walker = 22, Crawler = 12, Runner = 16, Hunter = 12, Bruiser = 10, Spitter = 6, Shardling = 10, MossBrute = 7, EmberWisp = 5 },
			},
			{
				MinWave = 25,
				MaxWave = 49,
				BaseEnemiesPerWave = 18,
				EnemiesPerWaveStep = 1,
				MaxAlive = 20,
				SpawnInterval = 2.8,
				BossAdditionalEnemies = 6,
				Weights = { Walker = 15, Crawler = 8, Runner = 14, Hunter = 10, Bruiser = 13, Spitter = 10, VenomSpitter = 7, Shardling = 9, MossBrute = 8, EmberWisp = 6 },
			},
			{
				MinWave = 50,
				MaxWave = 74,
				BaseEnemiesPerWave = 24,
				EnemiesPerWaveStep = 1,
				MaxAlive = 28,
				SpawnInterval = 2.4,
				BossAdditionalEnemies = 8,
				Weights = { Walker = 9, Crawler = 6, Runner = 12, Hunter = 11, Bruiser = 13, Spitter = 9, VenomSpitter = 6, Flyer = 9, Shardling = 8, MossBrute = 9, EmberWisp = 8 },
			},
			{
				MinWave = 75,
				BaseEnemiesPerWave = 30,
				EnemiesPerWaveStep = 1,
				MaxAlive = 36,
				SpawnInterval = 2.1,
				BossAdditionalEnemies = 10,
				Weights = { Walker = 5, Crawler = 5, Runner = 10, Hunter = 10, Bruiser = 13, Spitter = 8, VenomSpitter = 7, Flyer = 9, Bomber = 8, Shardling = 7, MossBrute = 10, EmberWisp = 8 },
			},
		},
		PartyRewardBonusPerPlayer = 0.1,
		PartyEnemyCountBonusPerPlayer = 0.1,

		BaseMaxAlive = 10,
		BaseSpawnInterval = 3.8,
		MinSpawnInterval = 1.1,
		WaveSpawnSpeedMultiplier = 10,
		MaxAlivePerStage = 2,

		BaseHealth = 100,
		BaseMoveSpeed = 4.5,
		BaseAttackDamage = 10,
		BaseAttackRange = 4.5,
		BaseAttackCooldown = 1.2,
		BaseRewardMoney = 25,
		BaseRewardXP = 20,

		DifficultyStepSeconds = 60,
		HealthScalePerStage = 0.01,
		SpeedScalePerStage = 0.05,
		DamageScalePerStage = 0.1,
		RewardScalePerStage = 0.08,
		SpawnRateScalePerStage = 0.12,

		RespawnDelayIfTeammateAlive = 60,
		FreeRespawnBaseSeconds = 10,
		FreeRespawnIncrementSeconds = 10,
		WipePurchaseWindowSeconds = 30,
		ReviveProducts = {
			SoloReviveProductId = 3565038680,
			TeamReviveProductId = 3565038815,
		},
		ReviveDisplayPrices = {
			SoloReviveRobux = 10,
			TeamReviveRobux = 50,
		},
		ReturnToLobbyDelayAfterWipe = 0,
		ReturnToLobbyDelayAfterVictory = 12,
		RestartDelayAfterWipe = 12,

		KillCreditTimeout = 15,
		MinSpawnDistanceToPlayer = 20,

		Variants = {
			Walker = {
				DisplayName = "Walker",
				TemplateModelName = "Troll Warlord",
				TemplateScale = 0.92,
				HealthMul = 1.0,
				MoveSpeedMul = 1.0,
				DamageMul = 1.0,
				RewardMul = 1.0,
				Color = { 77, 142, 74 },
				HeadColor = { 101, 170, 95 },
			},
			Crawler = {
				DisplayName = "Crawler",
				TemplateModelName = "Troll Warlord",
				TemplateScale = 0.7,
				HealthMul = 0.8,
				MoveSpeedMul = 0.75,
				DamageMul = 0.9,
				RewardMul = 1.1,
				ScaleY = 0.55,
				Color = { 96, 128, 67 },
				HeadColor = { 118, 162, 84 },
			},
			Runner = {
				DisplayName = "Runner",
				TemplateModelName = "Troll Warlord",
				TemplateScale = 0.78,
				HealthMul = 0.6,
				MoveSpeedMul = 2.15,
				DamageMul = 0.7,
				RewardMul = 1.3,
				Color = { 70, 120, 90 },
				HeadColor = { 88, 150, 110 },
			},
			Flyer = {
				DisplayName = "Flyer",
				TemplateModelName = "Dark Cursed Golem",
				TemplateScale = 0.82,
				IsFlyer = true,
				HealthMul = 0.7,
				MoveSpeedMul = 1.35,
				DamageMul = 0.85,
				RewardMul = 1.45,
				FlyHeight = 9,
				Color = { 95, 88, 160 },
				HeadColor = { 125, 118, 185 },
			},
			Spitter = {
				DisplayName = "Spitter",
				TemplateModelName = "Troll Warlord",
				TemplateScale = 0.9,
				IsSpitter = true,
				HealthMul = 1.0,
				MoveSpeedMul = 0.95,
				DamageMul = 0.65,
				RewardMul = 1.6,
				SpitRange = 42,
				SpitDamage = 14,
				SpitCooldown = 2.4,
				SpitProjectileSpeed = 52,
				Color = { 65, 130, 64 },
				HeadColor = { 94, 170, 94 },
			},
			VenomSpitter = {
				DisplayName = "Venom Spitter",
				TemplateModelName = "Troll Warlord",
				TemplateScale = 1.0,
				IsSpitter = true,
				HealthMul = 1.15,
				MoveSpeedMul = 0.9,
				DamageMul = 0.75,
				RewardMul = 1.9,
				SpitRange = 48,
				SpitDamage = 20,
				SpitCooldown = 2.9,
				SpitProjectileSpeed = 58,
				Color = { 52, 112, 62 },
				HeadColor = { 76, 145, 82 },
			},
			Hunter = {
				DisplayName = "Hunter",
				TemplateModelName = "Troll Warlord",
				TemplateScale = 0.86,
				HealthMul = 0.55,
				MoveSpeedMul = 2.35,
				DamageMul = 0.8,
				RewardMul = 1.45,
				Color = { 72, 102, 122 },
				HeadColor = { 104, 136, 156 },
			},
			Bruiser = {
				DisplayName = "Bruiser",
				TemplateModelName = "Troll Warlord",
				TemplateScale = 1.12,
				HealthMul = 1.9,
				MoveSpeedMul = 0.72,
				DamageMul = 1.55,
				RewardMul = 1.7,
				ScaleY = 1.2,
				Color = { 94, 89, 78 },
				HeadColor = { 126, 117, 101 },
			},
			Bomber = {
				DisplayName = "Bomber",
				TemplateModelName = "Troll Warlord",
				TemplateScale = 0.95,
				IsBomber = true,
				HealthMul = 0.9,
				MoveSpeedMul = 1.1,
				DamageMul = 0.8,
				RewardMul = 1.8,
				ExplosionRange = 10,
				ExplosionDamage = 45,
				ExplosionTriggerRange = 6.5,
				Color = { 160, 88, 74 },
				HeadColor = { 194, 118, 95 },
			},
			Shardling = {
				DisplayName = "Shardling",
				TemplateModelName = "Codex Shardling",
				ProceduralAnimationStyle = "Scuttle",
				TemplateScale = 0.9,
				HealthMul = 0.55,
				MoveSpeedMul = 2.2,
				DamageMul = 0.65,
				RewardMul = 1.25,
				AttackAnimationDuration = 0.38,
			},
			MossBrute = {
				DisplayName = "Moss Brute",
				TemplateModelName = "Codex Moss Brute",
				ProceduralAnimationStyle = "Stomp",
				TemplateScale = 1.0,
				HealthMul = 2.2,
				MoveSpeedMul = 0.68,
				DamageMul = 1.6,
				RewardMul = 1.8,
				AttackAnimationDuration = 0.62,
			},
			EmberWisp = {
				DisplayName = "Ember Wisp",
				TemplateModelName = "Codex Ember Wisp",
				ProceduralAnimationStyle = "Hover",
				TemplateScale = 0.95,
				IsFlyer = true,
				FlyHeight = 7,
				HealthMul = 0.75,
				MoveSpeedMul = 1.45,
				DamageMul = 0.9,
				RewardMul = 1.5,
				AttackAnimationDuration = 0.45,
			},
			AnimatedTroll = {
				DisplayName = "Animated Troll",
				TemplateModelName = "Codex Animated Troll",
				TemplateScale = 0.92,
				HealthMul = 1.0,
				MoveSpeedMul = 1.0,
				DamageMul = 1.0,
				RewardMul = 1.0,
				AttackAnimationDuration = 0.65,
			},
			BossBrute = {
				DisplayName = "Boss Brute",
				TemplateModelName = "Big Cursed Golem",
				TemplateScale = 1.18,
				IsBoss = true,
				HealthMul = 6.0,
				MoveSpeedMul = 0.9,
				DamageMul = 2.5,
				RewardMul = 3.0,
				BossCrystalDrop = 5,
				Color = { 120, 55, 55 },
				HeadColor = { 175, 90, 90 },
			},
		},

		DifficultySchedule = {
			{ MinTime = 0, Weights = { Walker = 76, Crawler = 20, Runner = 4 } },
			{ MinTime = 60, Weights = { Runner = 52, Hunter = 22, Walker = 14, Crawler = 12 } },
			{ MinTime = 120, Weights = { Walker = 38, Crawler = 16, Runner = 18, Hunter = 14, Bruiser = 8, Spitter = 6 } },
			{ MinTime = 180, Weights = { Walker = 24, Crawler = 12, Runner = 16, Hunter = 14, Bruiser = 14, Spitter = 10, VenomSpitter = 6, Flyer = 4 } },
			{ MinTime = 240, Weights = { Walker = 16, Crawler = 10, Runner = 14, Hunter = 14, Bruiser = 15, Spitter = 11, VenomSpitter = 8, Flyer = 8, Bomber = 4 } },
			{ MinTime = 300, Weights = { Walker = 10, Crawler = 8, Runner = 14, Hunter = 14, Bruiser = 16, Spitter = 10, VenomSpitter = 8, Flyer = 10, Bomber = 10 } },
		},
	},

	Ammo = {
		MagazinesEnabled = false,
		InfiniteReserve = true,
		SpawnPickups = false,
	},

	Pickups = {
		Enabled = false,
		SpawnInterval = 12,
		Lifetime = 45,
		MaxNearbyPerPlayer = 5,
		MinRadius = 8,
		MaxRadius = 16,
		DefaultAmmoAmount = 10,
	},

	OneTimeUpgrades = {
		Enabled = true,
		FolderName = "OneTimeUpgrades",
		Upgrades = {
			DamageShrine = {
				DisplayName = "Damage Shrine",
				PromptText = "Buy damage boost",
				Cost = 250,
				Position = { 36, 2, -24 },
				Size = { 7, 5, 7 },
				Color = { 255, 200, 90 },
				RangedLevels = 1,
				MeleeLevels = 1,
			},
		},
	},

	Debug = {
		GrantAllWeaponsOnSpawn = false,
		EnableStudioEnemySpawner = true,
		EnablePublishedEnemySpawner = true,
		EnemySpawnerAuthorizedUserIds = { 7414680949 },
	},

	DefaultOwnedWeapons = { "Bulava" },
	ShopOrder = { "Pistol", "Rifle", "Shotgun", "Sniper", "Bow", "Bulava" },

	Weapons = {
		Pistol = {
			Key = "Pistol",
			ToolName = "Pistol",
			TemplateToolName = "Pistol",
			DisplayName = "Pistol",
			Category = "Ranged",
			Price = 200,
			MaxMag = 12,
			StartReserve = 36,
			MaxReserve = 180,
			FireCooldown = 0.2,
			ReloadTime = 1.5,
			Range = 320,
			Damage = 22,
			Pellets = 1,
			SpreadDegrees = 1.5,
			AmmoPackPrice = 30,
			AmmoPackAmount = 24,
			FireAnimationId = "",
			ReloadAnimationId = "",
			ShotSoundId = "rbxassetid://2920959",
			ShotSoundVolume = 0.2,
			ShotSoundPlaybackSpeed = 1.04,
			ReloadSoundId = "",
		},

		Rifle = {
			Key = "Rifle",
			ToolName = "Rifle",
			TemplateToolName = "Assault Rifle",
			DisplayName = "Rifle",
			Category = "Ranged",
			Price = 450,
			MaxMag = 30,
			StartReserve = 90,
			MaxReserve = 360,
			FireCooldown = 0.09,
			ReloadTime = 2.2,
			Range = 380,
			Damage = 14,
			Pellets = 1,
			SpreadDegrees = 2.2,
			AmmoPackPrice = 55,
			AmmoPackAmount = 45,
			FireAnimationId = "",
			ReloadAnimationId = "",
			ShotSoundId = "rbxassetid://174295284",
			ShotSoundVolume = 0.12,
			ShotSoundPlaybackSpeed = 1.0,
			ReloadSoundId = "",
		},

		Shotgun = {
			Key = "Shotgun",
			ToolName = "Shotgun",
			TemplateToolName = "Shotgun",
			DisplayName = "Shotgun",
			Category = "Ranged",
			Price = 650,
			MaxMag = 6,
			StartReserve = 24,
			MaxReserve = 90,
			FireCooldown = 0.85,
			ReloadTime = 2.0,
			Range = 180,
			Damage = 12,
			Pellets = 7,
			SpreadDegrees = 7.5,
			AmmoPackPrice = 70,
			AmmoPackAmount = 12,
			FireAnimationId = "",
			ReloadAnimationId = "",
			ShotSoundId = "rbxassetid://240222925",
			ShotSoundVolume = 0.25,
			ShotSoundPlaybackSpeed = 1.0,
			BoltSoundId = "rbxassetid://10209881",
			BoltSoundVolume = 0.22,
			BoltSoundPlaybackSpeed = 1.0,
			BoltSoundDelay = 0.18,
			ReloadSoundId = "",
		},

		Sniper = {
			Key = "Sniper",
			ToolName = "Sniper",
			TemplateToolName = "Sniper",
			DisplayName = "Sniper",
			Category = "Ranged",
			Price = 900,
			MaxMag = 5,
			StartReserve = 20,
			MaxReserve = 80,
			FireCooldown = 1.2,
			ReloadTime = 2.7,
			Range = 700,
			Damage = 80,
			Pellets = 1,
			SpreadDegrees = 0.15,
			AmmoPackPrice = 95,
			AmmoPackAmount = 10,
			FireAnimationId = "",
			ReloadAnimationId = "",
			ShotSoundId = "rbxassetid://139711658",
			ShotSoundVolume = 0.27,
			ShotSoundPlaybackSpeed = 0.72,
			ReloadSoundId = "",
		},

		Bow = {
			Key = "Bow",
			ToolName = "Bow",
			TemplateToolName = "Automender",
			DisplayName = "Bow",
			Category = "Ranged",
			Price = 700,
			MaxMag = 1,
			StartReserve = 20,
			MaxReserve = 80,
			FireCooldown = 0.9,
			ReloadTime = 1.0,
			Range = 420,
			Damage = 45,
			Pellets = 1,
			SpreadDegrees = 0.9,
			AmmoPackPrice = 60,
			AmmoPackAmount = 10,
			FireAnimationId = "",
			ReloadAnimationId = "",
			ShotSoundId = "rbxassetid://131072992",
			ShotSoundVolume = 0.19,
			ShotSoundPlaybackSpeed = 1.0,
			ReloadSoundId = "",
		},

		Bulava = {
			Key = "Bulava",
			ToolName = "Bulava",
			TemplateToolName = "Sword",
			DisplayName = "Bulava",
			Category = "Melee",
			Price = 250,
			Damage = 40,
			Cooldown = 0.75,
			Range = 7,
			SwingAnimationId = "rbxassetid://522635514",
			SwingAltAnimationId = "rbxassetid://522638767",
			SwingSoundId = "rbxasset://sounds/swordslash.wav",
		},
	},
}

local additionalEnemyVariants = {
	Needleling = {
		DisplayName = "Needleling",
		TemplateModelName = "Codex Needleling",
		ProceduralAnimationStyle = "Scuttle",
		TemplateScale = 0.72,
		HealthMul = 0.45,
		MoveSpeedMul = 2.5,
		DamageMul = 0.55,
		RewardMul = 1.15,
		AttackAnimationDuration = 0.3,
	},
	DustMite = {
		DisplayName = "Dust Mite",
		TemplateModelName = "Codex Dust Mite",
		ProceduralAnimationStyle = "Scuttle",
		TemplateScale = 0.78,
		HealthMul = 0.65,
		MoveSpeedMul = 1.8,
		DamageMul = 0.7,
		RewardMul = 1.15,
		AttackAnimationDuration = 0.34,
	},
	ThornRunner = {
		DisplayName = "Thorn Runner",
		TemplateModelName = "Codex Thorn Runner",
		ProceduralAnimationStyle = "Scuttle",
		TemplateScale = 0.86,
		HealthMul = 0.55,
		MoveSpeedMul = 2.3,
		DamageMul = 0.8,
		RewardMul = 1.25,
		AttackAnimationDuration = 0.32,
	},
	Shellback = {
		DisplayName = "Shellback",
		TemplateModelName = "Codex Shellback",
		ProceduralAnimationStyle = "Scuttle",
		TemplateScale = 1.08,
		HealthMul = 1.4,
		MoveSpeedMul = 0.75,
		DamageMul = 1.0,
		RewardMul = 1.4,
		AttackAnimationDuration = 0.46,
	},
	FrostTick = {
		DisplayName = "Frost Tick",
		TemplateModelName = "Codex Frost Tick",
		ProceduralAnimationStyle = "Scuttle",
		TemplateScale = 0.82,
		HealthMul = 0.8,
		MoveSpeedMul = 1.6,
		DamageMul = 0.75,
		RewardMul = 1.25,
		AttackAnimationDuration = 0.36,
	},
	LavaCrawler = {
		DisplayName = "Lava Crawler",
		TemplateModelName = "Codex Lava Crawler",
		ProceduralAnimationStyle = "Scuttle",
		TemplateScale = 0.94,
		IsBomber = true,
		HealthMul = 0.9,
		MoveSpeedMul = 1.1,
		DamageMul = 0.9,
		RewardMul = 1.5,
		ExplosionRange = 9,
		ExplosionDamage = 38,
		ExplosionTriggerRange = 5.5,
		AttackAnimationDuration = 0.42,
	},
	BoneSkitter = {
		DisplayName = "Bone Skitter",
		TemplateModelName = "Codex Bone Skitter",
		ProceduralAnimationStyle = "Scuttle",
		TemplateScale = 0.9,
		HealthMul = 0.7,
		MoveSpeedMul = 2.0,
		DamageMul = 1.1,
		RewardMul = 1.35,
		AttackAnimationDuration = 0.34,
	},
	Stonekin = {
		DisplayName = "Stonekin",
		TemplateModelName = "Codex Stonekin",
		ProceduralAnimationStyle = "Stomp",
		TemplateScale = 0.82,
		HealthMul = 1.3,
		MoveSpeedMul = 0.9,
		DamageMul = 1.1,
		RewardMul = 1.35,
		AttackAnimationDuration = 0.5,
	},
	BogHulker = {
		DisplayName = "Bog Hulker",
		TemplateModelName = "Codex Bog Hulker",
		ProceduralAnimationStyle = "Stomp",
		TemplateScale = 1.05,
		HealthMul = 1.8,
		MoveSpeedMul = 0.65,
		DamageMul = 1.3,
		RewardMul = 1.55,
		AttackAnimationDuration = 0.62,
	},
	IronMauler = {
		DisplayName = "Iron Mauler",
		TemplateModelName = "Codex Iron Mauler",
		ProceduralAnimationStyle = "Stomp",
		TemplateScale = 1.08,
		HealthMul = 2.0,
		MoveSpeedMul = 0.7,
		DamageMul = 1.6,
		RewardMul = 1.7,
		AttackAnimationDuration = 0.6,
	},
	CrystalGuard = {
		DisplayName = "Crystal Guard",
		TemplateModelName = "Codex Crystal Guard",
		ProceduralAnimationStyle = "Stomp",
		TemplateScale = 1.12,
		HealthMul = 2.5,
		MoveSpeedMul = 0.55,
		DamageMul = 1.2,
		RewardMul = 1.8,
		AttackAnimationDuration = 0.65,
	},
	AshBrute = {
		DisplayName = "Ash Brute",
		TemplateModelName = "Codex Ash Brute",
		ProceduralAnimationStyle = "Stomp",
		TemplateScale = 1.0,
		HealthMul = 1.6,
		MoveSpeedMul = 0.85,
		DamageMul = 1.4,
		RewardMul = 1.55,
		AttackAnimationDuration = 0.56,
	},
	PlagueBearer = {
		DisplayName = "Plague Bearer",
		TemplateModelName = "Codex Plague Bearer",
		ProceduralAnimationStyle = "Stomp",
		TemplateScale = 0.96,
		IsSpitter = true,
		HealthMul = 1.1,
		MoveSpeedMul = 0.8,
		DamageMul = 0.7,
		RewardMul = 1.65,
		SpitRange = 44,
		SpitDamage = 16,
		SpitCooldown = 2.7,
		SpitProjectileSpeed = 54,
		AttackAnimationDuration = 0.52,
	},
	SandGolem = {
		DisplayName = "Sand Golem",
		TemplateModelName = "Codex Sand Golem",
		ProceduralAnimationStyle = "Stomp",
		TemplateScale = 1.15,
		HealthMul = 2.2,
		MoveSpeedMul = 0.6,
		DamageMul = 1.5,
		RewardMul = 1.75,
		AttackAnimationDuration = 0.66,
	},
	FrostWisp = {
		DisplayName = "Frost Wisp",
		TemplateModelName = "Codex Frost Wisp",
		ProceduralAnimationStyle = "Hover",
		TemplateScale = 0.78,
		IsFlyer = true,
		FlyHeight = 6,
		HealthMul = 0.65,
		MoveSpeedMul = 1.5,
		DamageMul = 0.7,
		RewardMul = 1.35,
		AttackAnimationDuration = 0.4,
	},
	VoidEye = {
		DisplayName = "Void Eye",
		TemplateModelName = "Codex Void Eye",
		ProceduralAnimationStyle = "Hover",
		TemplateScale = 0.9,
		IsFlyer = true,
		IsSpitter = true,
		FlyHeight = 7,
		HealthMul = 0.8,
		MoveSpeedMul = 1.2,
		DamageMul = 0.75,
		RewardMul = 1.6,
		SpitRange = 50,
		SpitDamage = 18,
		SpitCooldown = 3.0,
		SpitProjectileSpeed = 62,
		AttackAnimationDuration = 0.46,
	},
	SparkDrone = {
		DisplayName = "Spark Drone",
		TemplateModelName = "Codex Spark Drone",
		ProceduralAnimationStyle = "Hover",
		TemplateScale = 0.7,
		IsFlyer = true,
		FlyHeight = 7,
		HealthMul = 0.5,
		MoveSpeedMul = 2.0,
		DamageMul = 0.6,
		RewardMul = 1.35,
		AttackAnimationDuration = 0.34,
	},
	ToxicOrb = {
		DisplayName = "Toxic Orb",
		TemplateModelName = "Codex Toxic Orb",
		ProceduralAnimationStyle = "Hover",
		TemplateScale = 0.88,
		IsFlyer = true,
		IsSpitter = true,
		FlyHeight = 6,
		HealthMul = 0.75,
		MoveSpeedMul = 1.1,
		DamageMul = 0.8,
		RewardMul = 1.55,
		SpitRange = 46,
		SpitDamage = 21,
		SpitCooldown = 3.2,
		SpitProjectileSpeed = 48,
		AttackAnimationDuration = 0.48,
	},
	SolarWisp = {
		DisplayName = "Solar Wisp",
		TemplateModelName = "Codex Solar Wisp",
		ProceduralAnimationStyle = "Hover",
		TemplateScale = 0.92,
		IsFlyer = true,
		IsBomber = true,
		FlyHeight = 6,
		HealthMul = 0.9,
		MoveSpeedMul = 1.3,
		DamageMul = 1.0,
		RewardMul = 1.7,
		ExplosionRange = 11,
		ExplosionDamage = 48,
		ExplosionTriggerRange = 7,
		AttackAnimationDuration = 0.46,
	},
	StormShard = {
		DisplayName = "Storm Shard",
		TemplateModelName = "Codex Storm Shard",
		ProceduralAnimationStyle = "Hover",
		TemplateScale = 0.82,
		IsFlyer = true,
		FlyHeight = 8,
		HealthMul = 0.7,
		MoveSpeedMul = 1.8,
		DamageMul = 1.1,
		RewardMul = 1.6,
		AttackAnimationDuration = 0.38,
	},
}

local bossVariants = {
	BossStoneTitan = {
		DisplayName = "Stone Titan",
		TemplateModelName = "Codex Boss Stone Titan",
		ProceduralAnimationStyle = "Stomp",
		TemplateScale = 1.35,
		IsBoss = true,
		BossAbility = "Rockfall",
		HealthMul = 8.0,
		MoveSpeedMul = 0.62,
		DamageMul = 2.2,
		RewardMul = 4.0,
		BossCrystalDrop = 5,
		AttackAnimationDuration = 0.72,
	},
	BossStormColossus = {
		DisplayName = "Storm Colossus",
		TemplateModelName = "Codex Boss Storm Colossus",
		ProceduralAnimationStyle = "Stomp",
		TemplateScale = 1.28,
		IsBoss = true,
		BossAbility = "Shockwave",
		HealthMul = 7.5,
		MoveSpeedMul = 0.78,
		DamageMul = 2.0,
		RewardMul = 4.0,
		BossCrystalDrop = 6,
		AttackAnimationDuration = 0.68,
	},
	BossFlameWarden = {
		DisplayName = "Flame Warden",
		TemplateModelName = "Codex Boss Flame Warden",
		ProceduralAnimationStyle = "Stomp",
		TemplateScale = 1.22,
		IsBoss = true,
		BossAbility = "FlameLanes",
		HealthMul = 7.0,
		MoveSpeedMul = 0.85,
		DamageMul = 2.1,
		RewardMul = 4.2,
		BossCrystalDrop = 7,
		AttackAnimationDuration = 0.64,
	},
	BossBroodQueen = {
		DisplayName = "Brood Queen",
		TemplateModelName = "Codex Boss Brood Queen",
		ProceduralAnimationStyle = "Scuttle",
		TemplateScale = 1.55,
		IsBoss = true,
		BossAbility = "SummonBrood",
		HealthMul = 7.8,
		MoveSpeedMul = 0.9,
		DamageMul = 1.9,
		RewardMul = 4.3,
		BossCrystalDrop = 8,
		AttackAnimationDuration = 0.58,
	},
}

for variantKey, variant in pairs(additionalEnemyVariants) do
	config.Zombies.Variants[variantKey] = variant
end
for variantKey, variant in pairs(bossVariants) do
	config.Zombies.Variants[variantKey] = variant
end

config.Zombies.VariantIntroductions = {
	{ MinWave = 1, Weights = { Needleling = 10 } },
	{ MinWave = 2, Weights = { DustMite = 7 } },
	{ MinWave = 3, Weights = { ThornRunner = 9 } },
	{ MinWave = 4, Weights = { Shellback = 6 } },
	{ MinWave = 5, Weights = { FrostTick = 8 } },
	{ MinWave = 7, Weights = { LavaCrawler = 4 } },
	{ MinWave = 9, Weights = { BoneSkitter = 8 } },
	{ MinWave = 11, Weights = { Stonekin = 7 } },
	{ MinWave = 13, Weights = { BogHulker = 6 } },
	{ MinWave = 15, Weights = { IronMauler = 5 } },
	{ MinWave = 18, Weights = { CrystalGuard = 4 } },
	{ MinWave = 21, Weights = { AshBrute = 6 } },
	{ MinWave = 24, Weights = { PlagueBearer = 5 } },
	{ MinWave = 27, Weights = { SandGolem = 4 } },
	{ MinWave = 30, Weights = { FrostWisp = 7 } },
	{ MinWave = 34, Weights = { VoidEye = 4 } },
	{ MinWave = 38, Weights = { SparkDrone = 7 } },
	{ MinWave = 42, Weights = { ToxicOrb = 4 } },
	{ MinWave = 46, Weights = { SolarWisp = 4 } },
	{ MinWave = 50, Weights = { StormShard = 6 } },
}

config.Zombies.UseOnlyIntroducedVariants = true
config.Zombies.AllBossesWave = 50
config.Zombies.WaveEnemyCountCurve = {
	StartWave = 1,
	EndWave = 50,
	StartCount = 100,
	EndCount = 500,
}
config.Zombies.AliveCapCurve = {
	StartWave = 1,
	EndWave = 50,
	StartCount = 100,
	EndCount = 500,
}
config.Zombies.AbsoluteMaxAlive = 500
config.Zombies.DefaultSpawnRadius = 150
config.Zombies.DefaultSpawnPointCount = 8

config.Zombies.BossVariantOrder = {
	"BossStoneTitan",
	"BossStormColossus",
	"BossFlameWarden",
	"BossBroodQueen",
}

config.Zombies.BossAbilities = {
	Rockfall = {
		InitialDelay = 3.5,
		Cooldown = 8.0,
		TelegraphSeconds = 1.6,
		Radius = 6,
		RockCount = 3,
		RockHeight = 34,
		DamageMultiplier = 1.35,
		StunSeconds = 2.5,
	},
	Shockwave = {
		InitialDelay = 3.0,
		Cooldown = 7.0,
		TelegraphSeconds = 1.35,
		Radius = 22,
		DamageMultiplier = 1.15,
		KnockbackSpeed = 58,
	},
	FlameLanes = {
		InitialDelay = 2.8,
		Cooldown = 7.5,
		TelegraphSeconds = 1.45,
		Length = 38,
		Width = 5.5,
		LaneAngles = { -22, 0, 22 },
		DamageMultiplier = 1.0,
	},
	SummonBrood = {
		InitialDelay = 3.0,
		Cooldown = 9.5,
		TelegraphSeconds = 1.5,
		PortalRadius = 3.5,
		SummonCount = 4,
		SummonVariants = { "Needleling", "ThornRunner", "BoneSkitter", "Shellback" },
	},
}

config.Zombies.DebugMobPreviewOrder = {
	"Needleling",
	"DustMite",
	"ThornRunner",
	"Shellback",
	"FrostTick",
	"LavaCrawler",
	"BoneSkitter",
	"Stonekin",
	"BogHulker",
	"IronMauler",
	"CrystalGuard",
	"AshBrute",
	"PlagueBearer",
	"SandGolem",
	"FrostWisp",
	"VoidEye",
	"SparkDrone",
	"ToxicOrb",
	"SolarWisp",
	"StormShard",
}

return config
