return {
	Progression = {
		BaseXpForLevel = 100,
		XpGrowthPerLevel = 35,
		BaseWalkSpeed = 16,
		BaseMaxHealth = 100,
		SkillOrder = { "Speed", "MeleeDamage", "RangedDamage", "Health" },
		Skills = {
			Speed = {
				DisplayName = "Speed",
				MaxLevel = 8,
				WalkSpeedPerLevel = 1.8,
			},
			MeleeDamage = {
				DisplayName = "Melee Damage",
				MaxLevel = 8,
				DamageMultiplierPerLevel = 0.12,
			},
			RangedDamage = {
				DisplayName = "Ranged Damage",
				MaxLevel = 8,
				DamageMultiplierPerLevel = 0.1,
			},
			Health = {
				DisplayName = "Max Health",
				MaxLevel = 8,
				MaxHealthPerLevel = 20,
			},
		},
	},

	Lobby = {
		CombatPlaceId = 81561302455824,
		MaxPartySize = 6,
		DefaultPartySize = 2,
		DefaultPadCount = 2,
		QueueTouchDebounceSeconds = 1.0,
	},

	Classes = {
		DefaultClass = "Assault",
		Order = { "Assault", "Builder", "Healer", "Melee" },
		Definitions = {
			Assault = {
				DisplayName = "Assault",
				StarterWeapons = { "Rifle", "Bulava" },
			},
			Builder = {
				DisplayName = "Builder",
				StarterWeapons = { "Shotgun" },
			},
			Healer = {
				DisplayName = "Healer",
				StarterWeapons = { "Bow" },
			},
			Melee = {
				DisplayName = "Melee",
				StarterWeapons = { "Bulava" },
			},
		},
	},

	AchievementStats = {
		Order = {
			"RunsPlayed",
			"BestWave",
			"TotalKills",
			"BossKills",
		},
	},

	MetaProgression = {
		DataStoreName = "HeroicSurvivalProfile_v1",
		AutoSaveIntervalSeconds = 90,
		UpgradeOrder = { "Damage", "Health", "Speed" },
		Upgrades = {
			Damage = {
				DisplayName = "Damage",
				MaxLevel = 20,
				BaseCost = 5,
				CostStep = 5,
				RangedDamagePerLevel = 0.02,
				MeleeDamagePerLevel = 0.02,
			},
			Health = {
				DisplayName = "Health",
				MaxLevel = 20,
				BaseCost = 5,
				CostStep = 5,
				MaxHealthPerLevel = 4,
			},
			Speed = {
				DisplayName = "Speed",
				MaxLevel = 20,
				BaseCost = 5,
				CostStep = 5,
				WalkSpeedPerLevel = 0.12,
			},
		},
	},

	Zombies = {
		LobbyPlaceId = 135533599453315,
		DefaultDifficulty = "Medium",
		TargetWaveCount = 100,
		IntermissionSeconds = 12,
		BaseEnemiesPerWave = 8,
		EnemiesPerWaveStep = 1,
		BossWaveInterval = 10,
		BossAdditionalEnemies = 4,
		BossVariantKey = "BossBrute",
		Difficulties = {
			Easy = {
				DisplayName = "Easy",
				EnemyHealthMultiplier = 0.5,
				EnemyDamageMultiplier = 0.5,
				EnemyCountMultiplier = 0.5,
				RewardMultiplier = 0.5,
				CrystalMultiplier = 0.5,
			},
			Medium = {
				DisplayName = "Medium",
				EnemyHealthMultiplier = 1.0,
				EnemyDamageMultiplier = 1.0,
				EnemyCountMultiplier = 1.0,
				RewardMultiplier = 1.0,
				CrystalMultiplier = 1.0,
			},
			Hard = {
				DisplayName = "Hard",
				EnemyHealthMultiplier = 2.0,
				EnemyDamageMultiplier = 2.0,
				EnemyCountMultiplier = 2.0,
				RewardMultiplier = 2.0,
				CrystalMultiplier = 2.0,
			},
			Insane = {
				DisplayName = "Insane",
				EnemyHealthMultiplier = 4.0,
				EnemyDamageMultiplier = 4.0,
				EnemyCountMultiplier = 4.0,
				RewardMultiplier = 4.0,
				CrystalMultiplier = 4.0,
			},
		},
		WaveTable = {
			{
				MinWave = 1,
				MaxWave = 4,
				BaseEnemiesPerWave = 8,
				EnemiesPerWaveStep = 2,
				MaxAlive = 14,
				SpawnInterval = 2.9,
				BossAdditionalEnemies = 3,
				Weights = { Runner = 55, Hunter = 25, Walker = 10, Crawler = 10 },
			},
			{
				MinWave = 5,
				MaxWave = 9,
				BaseEnemiesPerWave = 10,
				EnemiesPerWaveStep = 2,
				MaxAlive = 16,
				SpawnInterval = 2.5,
				BossAdditionalEnemies = 4,
				Weights = { Runner = 45, Hunter = 25, Walker = 15, Crawler = 10, Bruiser = 5 },
			},
			{
				MinWave = 10,
				MaxWave = 24,
				BaseEnemiesPerWave = 11,
				EnemiesPerWaveStep = 1,
				MaxAlive = 13,
				SpawnInterval = 3.4,
				BossAdditionalEnemies = 5,
				Weights = { Walker = 32, Crawler = 16, Runner = 20, Hunter = 14, Bruiser = 12, Spitter = 6 },
			},
			{
				MinWave = 25,
				MaxWave = 49,
				BaseEnemiesPerWave = 18,
				EnemiesPerWaveStep = 1,
				MaxAlive = 20,
				SpawnInterval = 2.8,
				BossAdditionalEnemies = 6,
				Weights = { Walker = 22, Crawler = 12, Runner = 18, Hunter = 12, Bruiser = 16, Spitter = 12, VenomSpitter = 8 },
			},
			{
				MinWave = 50,
				MaxWave = 74,
				BaseEnemiesPerWave = 24,
				EnemiesPerWaveStep = 1,
				MaxAlive = 28,
				SpawnInterval = 2.4,
				BossAdditionalEnemies = 8,
				Weights = { Walker = 14, Crawler = 10, Runner = 16, Hunter = 14, Bruiser = 16, Spitter = 11, VenomSpitter = 7, Flyer = 12 },
			},
			{
				MinWave = 75,
				BaseEnemiesPerWave = 30,
				EnemiesPerWaveStep = 1,
				MaxAlive = 36,
				SpawnInterval = 2.1,
				BossAdditionalEnemies = 10,
				Weights = { Walker = 8, Crawler = 8, Runner = 14, Hunter = 14, Bruiser = 16, Spitter = 10, VenomSpitter = 8, Flyer = 12, Bomber = 10 },
			},
		},
		PartyRewardBonusPerPlayer = 0.1,
		PartyEnemyCountBonusPerPlayer = 0.1,

		BaseMaxAlive = 10,
		BaseSpawnInterval = 3.8,
		MinSpawnInterval = 1.1,
		MaxAlivePerStage = 2,

		BaseHealth = 100,
		BaseMoveSpeed = 4.5,
		BaseAttackDamage = 10,
		BaseAttackRange = 4.5,
		BaseAttackCooldown = 1.2,
		BaseRewardMoney = 25,
		BaseRewardXP = 20,

		DifficultyStepSeconds = 60,
		HealthScalePerStage = 0.12,
		SpeedScalePerStage = 0.05,
		DamageScalePerStage = 0.1,
		RewardScalePerStage = 0.08,
		SpawnRateScalePerStage = 0.12,

		RespawnDelayIfTeammateAlive = 60,
		FreeRespawnBaseSeconds = 10,
		FreeRespawnIncrementSeconds = 10,
		WipePurchaseWindowSeconds = 30,
		ReviveProducts = {
			SoloReviveProductId = 3565038680,
			TeamReviveProductId = 3565038815,
		},
		ReviveDisplayPrices = {
			SoloReviveRobux = 10,
			TeamReviveRobux = 50,
		},
		ReturnToLobbyDelayAfterWipe = 0,
		ReturnToLobbyDelayAfterVictory = 12,
		RestartDelayAfterWipe = 12,

		KillCreditTimeout = 15,
		MinSpawnDistanceToPlayer = 20,

		Variants = {
			Walker = {
				DisplayName = "Walker",
				TemplateModelName = "Troll Warlord",
				TemplateScale = 0.92,
				HealthMul = 1.0,
				MoveSpeedMul = 1.0,
				DamageMul = 1.0,
				RewardMul = 1.0,
				Color = { 77, 142, 74 },
				HeadColor = { 101, 170, 95 },
			},
			Crawler = {
				DisplayName = "Crawler",
				TemplateModelName = "Troll Warlord",
				TemplateScale = 0.7,
				HealthMul = 0.8,
				MoveSpeedMul = 0.75,
				DamageMul = 0.9,
				RewardMul = 1.1,
				ScaleY = 0.55,
				Color = { 96, 128, 67 },
				HeadColor = { 118, 162, 84 },
			},
			Runner = {
				DisplayName = "Runner",
				TemplateModelName = "Troll Warlord",
				TemplateScale = 0.78,
				HealthMul = 0.6,
				MoveSpeedMul = 2.15,
				DamageMul = 0.7,
				RewardMul = 1.3,
				Color = { 70, 120, 90 },
				HeadColor = { 88, 150, 110 },
			},
			Flyer = {
				DisplayName = "Flyer",
				TemplateModelName = "Dark Cursed Golem",
				TemplateScale = 0.82,
				IsFlyer = true,
				HealthMul = 0.7,
				MoveSpeedMul = 1.35,
				DamageMul = 0.85,
				RewardMul = 1.45,
				FlyHeight = 9,
				Color = { 95, 88, 160 },
				HeadColor = { 125, 118, 185 },
			},
			Spitter = {
				DisplayName = "Spitter",
				TemplateModelName = "Troll Warlord",
				TemplateScale = 0.9,
				IsSpitter = true,
				HealthMul = 1.0,
				MoveSpeedMul = 0.95,
				DamageMul = 0.65,
				RewardMul = 1.6,
				SpitRange = 42,
				SpitDamage = 14,
				SpitCooldown = 2.4,
				SpitProjectileSpeed = 52,
				Color = { 65, 130, 64 },
				HeadColor = { 94, 170, 94 },
			},
			VenomSpitter = {
				DisplayName = "Venom Spitter",
				TemplateModelName = "Troll Warlord",
				TemplateScale = 1.0,
				IsSpitter = true,
				HealthMul = 1.15,
				MoveSpeedMul = 0.9,
				DamageMul = 0.75,
				RewardMul = 1.9,
				SpitRange = 48,
				SpitDamage = 20,
				SpitCooldown = 2.9,
				SpitProjectileSpeed = 58,
				Color = { 52, 112, 62 },
				HeadColor = { 76, 145, 82 },
			},
			Hunter = {
				DisplayName = "Hunter",
				TemplateModelName = "Troll Warlord",
				TemplateScale = 0.86,
				HealthMul = 0.55,
				MoveSpeedMul = 2.35,
				DamageMul = 0.8,
				RewardMul = 1.45,
				Color = { 72, 102, 122 },
				HeadColor = { 104, 136, 156 },
			},
			Bruiser = {
				DisplayName = "Bruiser",
				TemplateModelName = "Troll Warlord",
				TemplateScale = 1.12,
				HealthMul = 1.9,
				MoveSpeedMul = 0.72,
				DamageMul = 1.55,
				RewardMul = 1.7,
				ScaleY = 1.2,
				Color = { 94, 89, 78 },
				HeadColor = { 126, 117, 101 },
			},
			Bomber = {
				DisplayName = "Bomber",
				TemplateModelName = "Troll Warlord",
				TemplateScale = 0.95,
				IsBomber = true,
				HealthMul = 0.9,
				MoveSpeedMul = 1.1,
				DamageMul = 0.8,
				RewardMul = 1.8,
				BossCrystalDrop = 1,
				ExplosionRange = 10,
				ExplosionDamage = 45,
				ExplosionTriggerRange = 6.5,
				Color = { 160, 88, 74 },
				HeadColor = { 194, 118, 95 },
			},
			BossBrute = {
				DisplayName = "Boss Brute",
				TemplateModelName = "Big Cursed Golem",
				TemplateScale = 1.18,
				IsBoss = true,
				HealthMul = 6.0,
				MoveSpeedMul = 0.9,
				DamageMul = 2.5,
				RewardMul = 3.0,
				BossCrystalDrop = 3,
				Color = { 120, 55, 55 },
				HeadColor = { 175, 90, 90 },
			},
		},

		DifficultySchedule = {
			{ MinTime = 0, Weights = { Walker = 76, Crawler = 20, Runner = 4 } },
			{ MinTime = 60, Weights = { Runner = 52, Hunter = 22, Walker = 14, Crawler = 12 } },
			{ MinTime = 120, Weights = { Walker = 38, Crawler = 16, Runner = 18, Hunter = 14, Bruiser = 8, Spitter = 6 } },
			{ MinTime = 180, Weights = { Walker = 24, Crawler = 12, Runner = 16, Hunter = 14, Bruiser = 14, Spitter = 10, VenomSpitter = 6, Flyer = 4 } },
			{ MinTime = 240, Weights = { Walker = 16, Crawler = 10, Runner = 14, Hunter = 14, Bruiser = 15, Spitter = 11, VenomSpitter = 8, Flyer = 8, Bomber = 4 } },
			{ MinTime = 300, Weights = { Walker = 10, Crawler = 8, Runner = 14, Hunter = 14, Bruiser = 16, Spitter = 10, VenomSpitter = 8, Flyer = 10, Bomber = 10 } },
		},
	},

	Ammo = {
		InfiniteReserve = true,
		SpawnPickups = false,
	},

	Pickups = {
		Enabled = false,
		SpawnInterval = 12,
		Lifetime = 45,
		MaxNearbyPerPlayer = 5,
		MinRadius = 8,
		MaxRadius = 16,
		DefaultAmmoAmount = 10,
	},

	Debug = {
		GrantAllWeaponsOnSpawn = true,
	},

	DefaultOwnedWeapons = { "Bulava" },
	ShopOrder = { "Pistol", "Rifle", "Shotgun", "Sniper", "Bow", "Bulava" },

	Weapons = {
		Pistol = {
			Key = "Pistol",
			ToolName = "Pistol",
			TemplateToolName = "Pistol",
			DisplayName = "Pistol",
			Category = "Ranged",
			Price = 200,
			MaxMag = 12,
			StartReserve = 36,
			MaxReserve = 180,
			FireCooldown = 0.2,
			ReloadTime = 1.5,
			Range = 320,
			Damage = 22,
			Pellets = 1,
			SpreadDegrees = 1.5,
			AmmoPackPrice = 30,
			AmmoPackAmount = 24,
			FireAnimationId = "",
			ReloadAnimationId = "",
			ShotSoundId = "rbxassetid://2920959",
			ShotSoundVolume = 0.2,
			ShotSoundPlaybackSpeed = 1.04,
			ReloadSoundId = "",
		},

		Rifle = {
			Key = "Rifle",
			ToolName = "Rifle",
			TemplateToolName = "Assault Rifle",
			DisplayName = "Rifle",
			Category = "Ranged",
			Price = 450,
			MaxMag = 30,
			StartReserve = 90,
			MaxReserve = 360,
			FireCooldown = 0.09,
			ReloadTime = 2.2,
			Range = 380,
			Damage = 14,
			Pellets = 1,
			SpreadDegrees = 2.2,
			AmmoPackPrice = 55,
			AmmoPackAmount = 45,
			FireAnimationId = "",
			ReloadAnimationId = "",
			ShotSoundId = "rbxassetid://174295284",
			ShotSoundVolume = 0.2,
			ShotSoundPlaybackSpeed = 1.0,
			ReloadSoundId = "",
		},

		Shotgun = {
			Key = "Shotgun",
			ToolName = "Shotgun",
			TemplateToolName = "Shotgun",
			DisplayName = "Shotgun",
			Category = "Ranged",
			Price = 650,
			MaxMag = 6,
			StartReserve = 24,
			MaxReserve = 90,
			FireCooldown = 0.85,
			ReloadTime = 2.0,
			Range = 180,
			Damage = 12,
			Pellets = 7,
			SpreadDegrees = 7.5,
			AmmoPackPrice = 70,
			AmmoPackAmount = 12,
			FireAnimationId = "",
			ReloadAnimationId = "",
			ShotSoundId = "rbxassetid://240222925",
			ShotSoundVolume = 0.25,
			ShotSoundPlaybackSpeed = 1.0,
			BoltSoundId = "rbxassetid://10209881",
			BoltSoundVolume = 0.22,
			BoltSoundPlaybackSpeed = 1.0,
			BoltSoundDelay = 0.18,
			ReloadSoundId = "",
		},

		Sniper = {
			Key = "Sniper",
			ToolName = "Sniper",
			TemplateToolName = "Sniper",
			DisplayName = "Sniper",
			Category = "Ranged",
			Price = 900,
			MaxMag = 5,
			StartReserve = 20,
			MaxReserve = 80,
			FireCooldown = 1.2,
			ReloadTime = 2.7,
			Range = 700,
			Damage = 80,
			Pellets = 1,
			SpreadDegrees = 0.15,
			AmmoPackPrice = 95,
			AmmoPackAmount = 10,
			FireAnimationId = "",
			ReloadAnimationId = "",
			ShotSoundId = "rbxassetid://139711658",
			ShotSoundVolume = 0.27,
			ShotSoundPlaybackSpeed = 0.72,
			ReloadSoundId = "",
		},

		Bow = {
			Key = "Bow",
			ToolName = "Bow",
			TemplateToolName = "Automender",
			DisplayName = "Bow",
			Category = "Ranged",
			Price = 700,
			MaxMag = 1,
			StartReserve = 20,
			MaxReserve = 80,
			FireCooldown = 0.9,
			ReloadTime = 1.0,
			Range = 420,
			Damage = 45,
			Pellets = 1,
			SpreadDegrees = 0.9,
			AmmoPackPrice = 60,
			AmmoPackAmount = 10,
			FireAnimationId = "",
			ReloadAnimationId = "",
			ShotSoundId = "rbxassetid://131072992",
			ShotSoundVolume = 0.19,
			ShotSoundPlaybackSpeed = 1.0,
			ReloadSoundId = "",
		},

		Bulava = {
			Key = "Bulava",
			ToolName = "Bulava",
			TemplateToolName = "Sword",
			DisplayName = "Bulava",
			Category = "Melee",
			Price = 250,
			Damage = 40,
			Cooldown = 0.75,
			Range = 7,
			SwingAnimationId = "rbxassetid://522635514",
			SwingAltAnimationId = "rbxassetid://522638767",
			SwingSoundId = "rbxasset://sounds/swordslash.wav",
		},
	},
}
